### ISSUE TITLE
Build plugin to check schema against supergraph

### ISSUE THREAD

**Issue by RaviPonduru** [apollographql/federation-jvm-spring-example#59]
Problem statement: ‘Spring for GraphQL’ is supporting multiple schema files (*.graphqls) under the location classpath:graphql/** , which is typically src/main/resources/graphql

How to merge multiple schema files into one schema file for CI pipeline ? Is there any build plugin available ?

CI workflow: https://www.apollographql.com/tutorials/voyage-part3/06-schema-checks-in-ci

**Comment by dariuszkuc** [comment]
Hello 👋 
There is no built-in functionality to do it. You would need to write some short script/app to merge the schema + transform it to get the final federated schema.

Since you need the schema artifact, it doesn't matter in which language you implement it. In order to do it using GraphQL Java see

* GraphQL Java docs how to [load schema from multiple SDL files](https://www.graphql-java.com/documentation/schema#modularising-the-schema-sdl)
* Federation JVM docs how to [transform the schema to federated one](https://github.com/apollographql/federation-jvm#creating-federated-schemas)
* then you can just use GraphQL Java `SchemaPrinter` to print the final schema back to a SDL format
