### ISSUE TITLE
Why .resolveEntityType(env -> null) ?

### ISSUE THREAD

**Issue by klys-equinix** [apollographql/federation-jvm-spring-example#71]
What is the purpose of this DataFetcher resolving entities to null in the Products part of the example?
https://github.com/apollographql/federation-jvm-spring-example/blob/366330c8f0df682990bbb2f2253a07ddfa58835f/products-subgraph/src/main/java/com/example/products/GraphQLConfiguration.java#L17

As I understand, it would mean that if the subgraph is hit with entities query it will always return a null result?
What is the purpose of such DataFetcher?

**Comment by dariuszkuc** [comment]
Hello 👋 
That was just an oversimplification due to the simple example. Technically, whenever you define an entity you should have valid `_entities` resolver (and `_Entity` union type resolver). `_entities` query is used as an extra entry point to a federated subgraph. 

Router attempts to create optimal query plan based on the incoming request. In our simple example, only `products` subgraph defines a root query and as such we will never have a query plan that will go back from `reviews` subgraph to a `product` subgraph. Another case when `_entities` resolver and `_Entity` union type resolver will not be used is when you define non-resolvable entity (see: [docs](https://www.apollographql.com/docs/federation/entities#referencing-an-entity-without-contributing-fields)). 

Since those are generally exceptions to the rule, `federation-jvm` explicitly requires users to always provide those two entities.
